ci: check that readme update was executed if needed

diff --git a/.forgejo/workflows/build-and-tests.yaml b/.forgejo/workflows/build-and-tests.yaml
--- a/.forgejo/workflows/build-and-tests.yaml
+++ b/.forgejo/workflows/build-and-tests.yaml
@@ -19,3 +19,11 @@ jobs:
         run: cargo build --verbose
       - name: Test the workspace
         run: cargo test --verbose
+      - name: Check for up-to-date readme
+        run: |
+          ./update-readme.sh
+          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then
+            echo "::warning::$(git status --untracked-files=no --porcelain)"
+            echo "::error title=Changed files::There are changed files in the repository. Readme not up to date?"
+            exit 1
+          fi
